- name: variables from inventory
  hosts: localhost
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "Hi, we are learing {{Course}} from trainer {{Trainer}},Duration is {{Duration}}"