- name: variables from arguments
  hosts: localhost
  tasks:
  - name: get from args
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"
      # pass variables as argumetns while excuting as -e PERSON=Ramesh WHISHES=Morning
      