- name: variable preference
  hosts: localhost
  vars:
    WISHES: "Morning from PLAY Variable"
  vars_files:
  - vars.yaml
  vars_prompt:
   - name: WISHES
     prompt: Please enter WISHES
     private: false
  tasks:
  - name: check preference
    vars:
      WISHES: "Morning from TASK Variable"
    ansible.builtin.debug:
      msg: "Hello, Good {{WISHES}}"

#Preferences:
#1.Arguments
#2.Task level
#3.variable file
#4.Prompt
#5.Play level
#6.Inventory
#7.Role level
