- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
      msg: "User info:{{USER}}" #in error "rc=1" , "rc=0" are like exit status 

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #Condition
    
  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"
