- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: "{{ item.state }}"
  loop:
  - { name: 'mysql', state: 'latest'} #item
  - { name: 'nginx', state: 'absent'}
  - { name: 'postfix', state: 'absent'}